### PR TITLE
 Add: resources/fs-uae.dat

### PR DESCRIPTION
**Pull request by repojohnray**

### CODE REVIEW

**Comment by garbear** [comment]
Thanks! @fetzerch OK to pull in the metadata that is normally generated?

**Comment by fetzerch** [comment]
Sure

**Comment by garbear** [comment]
Cool. When FS-UAE compiles again we can commit the updated changes.

**Comment by garbear** [comment]
@repojohnray Shouldn't the .dat file go in a `resources/system` folder for consistency?

**Comment by repojohnray** [comment]
You are right; This is the proper path, I will update the path search.

**Comment by repojohnray** [comment]
This seems to be 'usable' on a patched S905 CoreElec distribution too.

Is this OK on your side?

**Comment by garbear** [comment]
Are you going to move fs-uae.dat to the system/ folder?

**Comment by repojohnray** [comment]
repojohnray/game.libretro.fsuae updated. Is this fine on your side?

**Comment by garbear** [comment]
Looks great. thanks!

**Pull request merged**
